### PR TITLE
v10 compatibility

### PR DESCRIPTION
**Pull request by kaelad02**
Update to be compatible with v10

- update the manifest file
- update the code for the DataModel changes (e.g. removing `.data` where appropriate)
- add a `ATLUpdate#v10Update` function
- update the the preset editor to use v10 token keys and change it to look like the normal token settings app

### CODE REVIEW

**Comment by kaelad02** [comment]
The only thing left I can think of is to update the dialog in `GeneratePreset` to include the changes. I suspect that's not frequently used so you could update that later. I'll see if I can get it done later today and include it here

**Comment by etriebe** [comment]
What's the status of this? Have we heard from @kandashi if they'll be able to review?

**Comment by kaelad02** [comment]
I just saw a post in his Discord server that he's got some time to look at v10 updates, so hopefully "soon."

**Comment by kaelad02** [comment]
@kandashi I worked on the preset editor code and got it working. I replaced the dialog in `GeneratePreset` with a `FormApplication` that looks like a trimmed-down version of the token settings app. Here's a screenshot of what it looks like.

image

Are you okay with me pushing this to include as part of this PR or would you prefer I make a new one so you can review it separately?

**Comment by kandashi** [comment]
> @kandashi I worked on the preset editor code and got it working. I replaced the dialog in `GeneratePreset` with a `FormApplication` that looks like a trimmed-down version of the token settings app. Here's a screenshot of what it looks like.
> 
> image
> 
> Are you okay with me pushing this to include as part of this PR or would you prefer I make a new one so you can review it separately?

Hey, if you could include that it would be amazing. If you pull that accross I can merge and get a release sorted

**Comment by kaelad02** [comment]
Done, pushed the changes up. I realized last minute I needed to update the GitHub Action to include `templates/` in the zip file.

**Comment by kaelad02** [comment]
Fixed a bug when setting `ATL.sight.visionMode`. If you set it to `darkvision`, for example, you'd still see the map in color. It turns out that the token configuration app also updates some of the advanced vision options that are necessary for the `visionMode` change to work. It's unfortunate that `TokenDocument` doesn't take care of this automatically. They did provide a function, `TokenDocument#updateVisionMode` that will do it but I didn't use it since it triggers it's own `update` on the token document. That didn't seem like the best use here, so I just copied it's behavior, pulling those default values and setting them, kind of like what `preset` does.

**Comment by kaelad02** [comment]
Something else...
DAE has special support for this module's keys. While a module can supply an array of keys on its own, you don't get default values or drop-downs for things like `ATL.preset` does. We could take it over, but having the drop-down for preset seems nice. After merging this PR, we should get DAE updated with the key changes that v10 made.

**Comment by CaosFR** [comment]
@kandashi Hi, any news for the merge ?

**Comment by LanMan04** [comment]
@kandashi : You work is greatly appreciated, any update on the merge would be fantastic.

**Comment by LanMan04** [comment]
FYI!  From MrPrimate:
-----------------------
Finally, there is a temporary collection of fixes, primarily by @Kaelad, for Active-Auras and Active Token Effects for v10. These modules are beloved by those of us using a lot of automation, but Kandashi, the author, cannot update them right now due to RL pressures. If you want to use these in your v10 environment, the links are:

- Active Auras: https://github.com/MrPrimate/Active-Auras/releases/download/v0.4.22/module.json 

- Active Token Effects/Lighting: https://github.com/MrPrimate/Active-Token-Lighting/releases/download/v0.4.02/module.json

**Comment by MrPrimate** [comment]
Latest commits at https://github.com/MrPrimate/Active-Token-Lighting/releases/download/v0.4.03/module.json

**Comment by rinnocenti** [comment]
> Latest commits at https://github.com/MrPrimate/Active-Token-Lighting/releases/download/v0.4.03/module.json
@MrPrimate I don't know if you are keeping this module but there is a very annoying bug happening in these versions.
image

if the token has an image from a wildcard (eg images/dragons/*)

when apply some light effect it loses the token texture and returns with the default mystery man texture
image

**Comment by LukasPrism** [comment]
This is probably related to other issues which AFAIK are unresolved, due to ATL reverting to the prototype rather than the token as it was prior to the effect being applied

**Pull request merged**
